/*
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef __INC_BOARD_H
#define __INC_BOARD_H

#include <soc.h>

/* Push button switch 0 */
#define SW0_GPIO_PIN     27
#define SW0_GPIO_NAME    CONFIG_GPIO_NRF5_P0_DEV_NAME
#define SW0_GPIO_PIN_PUD GPIO_PUD_PULL_UP

/* Onboard GREEN LED 0 */
#define LED0_GPIO_PIN  11
#define LED0_GPIO_PORT CONFIG_GPIO_NRF5_P1_DEV_NAME
#define LED_GREEN_PIN	LED0_GPIO_PIN
#define LED_GREEN_PORT 	LED0_GPIO_PORT

/* Onboard BLUE LED 1 */
#define LED1_GPIO_PIN  12
#define LED1_GPIO_PORT CONFIG_GPIO_NRF5_P1_DEV_NAME
#define LED_BLUE_PIN	LED1_GPIO_PIN
#define LED_BLUE_PORT 	LED1_GPIO_PORT

/* Onboard RED LED 2 */
#define LED2_GPIO_PIN  13
#define LED2_GPIO_PORT CONFIG_GPIO_NRF5_P1_DEV_NAME
#define LED_RED_PIN		LED2_GPIO_PIN
#define LED_RED_PORT 	LED2_GPIO_PORT

#define LED_GREEN		LED0_GPIO_PIN
#define LED_BLUE		LED1_GPIO_PIN
#define LED_RED			LED2_GPIO_PIN
#define LEDS_PORT		CONFIG_GPIO_NRF5_P1_DEV_NAME

#define	MUX_RESET_PORT	CONFIG_GPIO_NRF5_P0_DEV_NAME
#define	MUX_RESET_PIN	26

/* Sensors power pins */
#define SHT_POWER_PORT	CONFIG_GPIO_NRF5_P0_DEV_NAME
#define SHT_POWER_PIN	13
#define SHT_I2C_CHANNEL	0

#define OPT_POWER_PORT	CONFIG_GPIO_NRF5_P1_DEV_NAME
#define OPT_POWER_PIN	10
#define OPT_I2C_CHANNEL	2

#define CCS_POWER_PORT	CONFIG_GPIO_NRF5_P0_DEV_NAME
#define CCS_POWER_PIN	14
#define CCS_I2C_CHANNEL	1
#define CCS_WAKE_PORT	CONFIG_GPIO_NRF5_P0_DEV_NAME
#define CCS_WALE_PIN	11

#define PYD_POWER_PORT	CONFIG_GPIO_NRF5_P0_DEV_NAME
#define PYD_POWER_PIN	21

#define MIC_POWER_PORT	CONFIG_GPIO_NRF5_P0_DEV_NAME
#define MIC_POWER_PIN	15

#define MIC_OUTPUT_PORT	CONFIG_GPIO_NRF5_P1_DEV_NAME
#define MIC_OUTPUT_PIN	29

#define PAC1934_POWER_PORT	CONFIG_GPIO_NRF5_P0_DEV_NAME
#define PAC1934_POWER_PIN	6

#define DISABLE_BOOST_PORT	CONFIG_GPIO_NRF5_P0_DEV_NAME
#define DISABLE_BOOST_PIN	19

#define EN_VDDH_PORT	CONFIG_GPIO_NRF5_P0_DEV_NAME
#define EN_VDDH_PIN		23

#endif /* __INC_BOARD_H */
